2022-02-05 16:46:37,580:DEBUG:certbot._internal.main:certbot version: 1.22.0
2022-02-05 16:46:37,581:DEBUG:certbot._internal.main:Location of certbot entry point: /usr/local/bin/certbot
2022-02-05 16:46:37,581:DEBUG:certbot._internal.main:Arguments: ['--webroot', '--webroot-path=/var/www/certbot', '--email', 'renanhconstancio@goamil.com', '--agree-tos', '--no-eff-email', '-d', 'apivendas.test', '-d', 'www.apivendas.test']
2022-02-05 16:46:37,581:DEBUG:certbot._internal.main:Discovered plugins: PluginsRegistry(PluginEntryPoint#manual,PluginEntryPoint#null,PluginEntryPoint#standalone,PluginEntryPoint#webroot)
2022-02-05 16:46:38,199:DEBUG:certbot._internal.log:Root logging level set at 30
2022-02-05 16:46:38,224:DEBUG:certbot._internal.plugins.selection:Requested authenticator webroot and installer None
2022-02-05 16:46:38,231:DEBUG:certbot._internal.plugins.selection:Single candidate plugin: * webroot
Description: Place files in webroot directory
Interfaces: Authenticator, Plugin
Entry point: webroot = certbot._internal.plugins.webroot:Authenticator
Initialized: <certbot._internal.plugins.webroot.Authenticator object at 0x7f82df2d5a90>
Prep: True
2022-02-05 16:46:38,233:DEBUG:certbot._internal.plugins.selection:Selected authenticator <certbot._internal.plugins.webroot.Authenticator object at 0x7f82df2d5a90> and installer None
2022-02-05 16:46:38,235:INFO:certbot._internal.plugins.selection:Plugins selected: Authenticator webroot, Installer None
2022-02-05 16:46:38,338:DEBUG:certbot._internal.main:Picked account: <Account(RegistrationResource(body=Registration(key=None, contact=(), agreement=None, status=None, terms_of_service_agreed=None, only_return_existing=None, external_account_binding=None), uri='https://acme-v02.api.letsencrypt.org/acme/acct/395931490', new_authzr_uri=None, terms_of_service=None), f1ca923811e923aa5bdd49716b3d962b, Meta(creation_dt=datetime.datetime(2022, 2, 5, 16, 29, 15, tzinfo=<UTC>), creation_host='bad2fcb2756b', register_to_eff=None))>
2022-02-05 16:46:38,341:DEBUG:acme.client:Sending GET request to https://acme-v02.api.letsencrypt.org/directory.
2022-02-05 16:46:38,347:DEBUG:urllib3.connectionpool:Starting new HTTPS connection (1): acme-v02.api.letsencrypt.org:443
2022-02-05 16:46:39,544:DEBUG:urllib3.connectionpool:https://acme-v02.api.letsencrypt.org:443 "GET /directory HTTP/1.1" 200 658
2022-02-05 16:46:39,548:DEBUG:acme.client:Received response:
HTTP 200
Server: nginx
Date: Sat, 05 Feb 2022 16:46:40 GMT
Content-Type: application/json
Content-Length: 658
Connection: keep-alive
Cache-Control: public, max-age=0, no-cache
X-Frame-Options: DENY
Strict-Transport-Security: max-age=604800

{
  "4A2pz75M-Oo": "https://community.letsencrypt.org/t/adding-random-entries-to-the-directory/33417",
  "keyChange": "https://acme-v02.api.letsencrypt.org/acme/key-change",
  "meta": {
    "caaIdentities": [
      "letsencrypt.org"
    ],
    "termsOfService": "https://letsencrypt.org/documents/LE-SA-v1.2-November-15-2017.pdf",
    "website": "https://letsencrypt.org"
  },
  "newAccount": "https://acme-v02.api.letsencrypt.org/acme/new-acct",
  "newNonce": "https://acme-v02.api.letsencrypt.org/acme/new-nonce",
  "newOrder": "https://acme-v02.api.letsencrypt.org/acme/new-order",
  "revokeCert": "https://acme-v02.api.letsencrypt.org/acme/revoke-cert"
}
2022-02-05 16:46:39,571:DEBUG:certbot._internal.display.obj:Notifying user: Requesting a certificate for apivendas.test and www.apivendas.test
2022-02-05 16:46:39,739:DEBUG:certbot.crypto_util:Generating RSA key (2048 bits): /etc/letsencrypt/keys/0002_key-certbot.pem
2022-02-05 16:46:39,810:DEBUG:certbot.crypto_util:Creating CSR: /etc/letsencrypt/csr/0002_csr-certbot.pem
2022-02-05 16:46:39,817:DEBUG:acme.client:Requesting fresh nonce
2022-02-05 16:46:39,819:DEBUG:acme.client:Sending HEAD request to https://acme-v02.api.letsencrypt.org/acme/new-nonce.
2022-02-05 16:46:40,043:DEBUG:urllib3.connectionpool:https://acme-v02.api.letsencrypt.org:443 "HEAD /acme/new-nonce HTTP/1.1" 200 0
2022-02-05 16:46:40,049:DEBUG:acme.client:Received response:
HTTP 200
Server: nginx
Date: Sat, 05 Feb 2022 16:46:41 GMT
Connection: keep-alive
Cache-Control: public, max-age=0, no-cache
Link: <https://acme-v02.api.letsencrypt.org/directory>;rel="index"
Replay-Nonce: 0001glLp8nKKqYtWByIRObJJri1KQskMDymhXUJI2dkuZgU
X-Frame-Options: DENY
Strict-Transport-Security: max-age=604800


2022-02-05 16:46:40,051:DEBUG:acme.client:Storing nonce: 0001glLp8nKKqYtWByIRObJJri1KQskMDymhXUJI2dkuZgU
2022-02-05 16:46:40,053:DEBUG:acme.client:JWS payload:
b'{\n  "identifiers": [\n    {\n      "type": "dns",\n      "value": "apivendas.test"\n    },\n    {\n      "type": "dns",\n      "value": "www.apivendas.test"\n    }\n  ]\n}'
2022-02-05 16:46:40,060:DEBUG:acme.client:Sending POST request to https://acme-v02.api.letsencrypt.org/acme/new-order:
{
  "protected": "eyJhbGciOiAiUlMyNTYiLCAia2lkIjogImh0dHBzOi8vYWNtZS12MDIuYXBpLmxldHNlbmNyeXB0Lm9yZy9hY21lL2FjY3QvMzk1OTMxNDkwIiwgIm5vbmNlIjogIjAwMDFnbExwOG5LS3FZdFdCeUlST2JKSnJpMUtRc2tNRHltaFhVSkkyZGt1WmdVIiwgInVybCI6ICJodHRwczovL2FjbWUtdjAyLmFwaS5sZXRzZW5jcnlwdC5vcmcvYWNtZS9uZXctb3JkZXIifQ",
  "signature": "dPTwL07dCqTeX7TwmIdW9_-Kj-Vpkk0lagDcI1PYHrz7HvoJQgEh8xuJgh-MKeNsZx54fMveTuzgm1AYir_oPk6DB50_bMHeBWT3q8ThkeFMZhPSHXSa_NLMFHa2Gn1hAV8q6oM71yJ1PVkjX-VMPMlLDkSYiM7PEZMC6sVTf2UlnKJaR4Ys2jhNVZl4FiE45PQDUX7kcY-tvQSwwbNLu6K_11vPLG7tjNI3mzXf-CuCRNEVc4VfYTJyL74S8UTS-fFOlTv3HaaFAJUCKA9Nf0VfoBwZfMnCUhkFlz9ObrI-nRLr5MQJADwoKZAaeG6FM6HrZBm1IUnOYWGrnJnERQ",
  "payload": "ewogICJpZGVudGlmaWVycyI6IFsKICAgIHsKICAgICAgInR5cGUiOiAiZG5zIiwKICAgICAgInZhbHVlIjogImFwaXZlbmRhcy50ZXN0IgogICAgfSwKICAgIHsKICAgICAgInR5cGUiOiAiZG5zIiwKICAgICAgInZhbHVlIjogInd3dy5hcGl2ZW5kYXMudGVzdCIKICAgIH0KICBdCn0"
}
2022-02-05 16:46:40,351:DEBUG:urllib3.connectionpool:https://acme-v02.api.letsencrypt.org:443 "POST /acme/new-order HTTP/1.1" 400 888
2022-02-05 16:46:40,353:DEBUG:acme.client:Received response:
HTTP 400
Server: nginx
Date: Sat, 05 Feb 2022 16:46:41 GMT
Content-Type: application/problem+json
Content-Length: 888
Connection: keep-alive
Boulder-Requester: 395931490
Cache-Control: public, max-age=0, no-cache
Link: <https://acme-v02.api.letsencrypt.org/directory>;rel="index"
Replay-Nonce: 0001UExE6Wsnv-nZUrBe21H1bwLhrFMRirJy8PLBySWFbLQ

{
  "type": "urn:ietf:params:acme:error:rejectedIdentifier",
  "detail": "Error creating new order :: Cannot issue for \"apivendas.test\": Domain name does not end with a valid public suffix (TLD) (and 1 more problems. Refer to sub-problems for more information.)",
  "status": 400,
  "subproblems": [
    {
      "type": "urn:ietf:params:acme:error:rejectedIdentifier",
      "detail": "Error creating new order :: Domain name does not end with a valid public suffix (TLD)",
      "status": 400,
      "identifier": {
        "type": "dns",
        "value": "apivendas.test"
      }
    },
    {
      "type": "urn:ietf:params:acme:error:rejectedIdentifier",
      "detail": "Error creating new order :: Domain name does not end with a valid public suffix (TLD)",
      "status": 400,
      "identifier": {
        "type": "dns",
        "value": "www.apivendas.test"
      }
    }
  ]
}
2022-02-05 16:46:40,360:DEBUG:certbot._internal.log:Exiting abnormally:
Traceback (most recent call last):
  File "/usr/local/bin/certbot", line 33, in <module>
    sys.exit(load_entry_point('certbot', 'console_scripts', 'certbot')())
  File "/opt/certbot/src/certbot/certbot/main.py", line 19, in main
    return internal_main.main(cli_args)
  File "/opt/certbot/src/certbot/certbot/_internal/main.py", line 1632, in main
    return config.func(config, plugins)
  File "/opt/certbot/src/certbot/certbot/_internal/main.py", line 1491, in certonly
    lineage = _get_and_save_cert(le_client, config, domains, certname, lineage)
  File "/opt/certbot/src/certbot/certbot/_internal/main.py", line 139, in _get_and_save_cert
    lineage = le_client.obtain_and_enroll_certificate(domains, certname)
  File "/opt/certbot/src/certbot/certbot/_internal/client.py", line 496, in obtain_and_enroll_certificate
    cert, chain, key, _ = self.obtain_certificate(domains)
  File "/opt/certbot/src/certbot/certbot/_internal/client.py", line 424, in obtain_certificate
    orderr = self._get_order_and_authorizations(csr.data, self.config.allow_subset_of_names)
  File "/opt/certbot/src/certbot/certbot/_internal/client.py", line 458, in _get_order_and_authorizations
    orderr = self.acme.new_order(csr_pem)
  File "/opt/certbot/src/acme/acme/client.py", line 936, in new_order
    return cast(ClientV2, self.client).new_order(csr_pem)
  File "/opt/certbot/src/acme/acme/client.py", line 702, in new_order
    response = self._post(self.directory['newOrder'], order)
  File "/opt/certbot/src/acme/acme/client.py", line 101, in _post
    return self.net.post(*args, **kwargs)
  File "/opt/certbot/src/acme/acme/client.py", line 1269, in post
    return self._post_once(*args, **kwargs)
  File "/opt/certbot/src/acme/acme/client.py", line 1283, in _post_once
    response = self._check_response(response, content_type=content_type)
  File "/opt/certbot/src/acme/acme/client.py", line 1128, in _check_response
    raise messages.Error.from_json(jobj)
acme.messages.Error: urn:ietf:params:acme:error:rejectedIdentifier :: The server will not issue certificates for the identifier :: Error creating new order :: Cannot issue for "apivendas.test": Domain name does not end with a valid public suffix (TLD) (and 1 more problems. Refer to sub-problems for more information.)
2022-02-05 16:46:40,389:ERROR:certbot._internal.log:An unexpected error occurred:
2022-02-05 16:46:40,390:ERROR:certbot._internal.log:The server will not issue certificates for the identifier :: Error creating new order :: Cannot issue for "apivendas.test": Domain name does not end with a valid public suffix (TLD) (and 1 more problems. Refer to sub-problems for more information.)
